import { init } from 'z3-solver'

export const initz3 = init
export const context = name => z3 => () => new z3.Context(name)
export const solver = ctx => () => new ctx.Solver()
export const solverAdd = v => solver => () => solver.add(v)
export const solverCheck = solver => () => solver.check()
export const solverModel = solver => () => solver.model()
export const showModel = model => () => model.toString()
export const evalInt = model => v => () => model.eval(v).value()
export const mkIntVar = context => name => () => context.Int.const(name)
export const mkBoolVar = context => name => () => context.Bool.const(name)
export const and_ = context => a => b => () => context.And(a, b)
export const or_ = context => a => b => () => context.Or(a, b)
export const not_ = context => a => () => context.Not(a)
export const distinct = context => a => () => context.Distinct(...a)
export const unsafeEq = a => b => () => a.eq(b)
export const unsafeNeq = a => b => () => a.neq(b)
export const unsafeLe = a => b => () => a.le(b)
export const unsafeGe = a => b => () => a.ge(b)
export const unsafeLt = a => b => () => a.lt(b)
export const unsafeGt = a => b => () => a.gt(b)
export const unsafeAdd = a => b => () => a.add(b)
export const unsafeMul = a => b => () => a.mul(b)